### PR TITLE
Certification informations.

### PR DESCRIPTION
**Pull request by apat59**
Hi guys,
Request from the GLS Team. Already talked about this to Emmanuel few weeks ago.
The idea is simply to bring some marketing efforts around the JPA certification.

### CODE REVIEW

**Comment by sebersole** [comment]
Are these trainings limited to ORM?

**Comment by emmanuelbernard** [comment]
http://fontawesome.io/icon/check-circle-o/ might be better as an icon but it conflicts a bit with Hibernate Validator's :(

**Comment by emmanuelbernard** [comment]
Actually if we could stack the certificate and the check mark icons, it might be better. I tried quickly but it did not work in my allotted time.

BTW, I find your use of the icon on the title of the certification page a bit strange. Was it intended for it to be last on the line?

**Comment by apat59** [comment]
About the icon in the title, it's simply a mimic of the paid support page.
I'm going to give a try here about stacking check+certificate.

Steve, yes this is limited to ORM.

**Comment by apat59** [comment]
was
< span class="icon-stack icon-lg">
< i class="icon icon-check icon-stack-1x"></ i>
< i class="icon icon-certificate icon-stack-2x icon-inverse"></ i>
< / span> 
http://www.redhat.com/training/certifications/jbcd-persistence/ <br>

**Comment by emmanuelbernard** [comment]
@apat59 interesting, the icon at the end works for small titles but looks a bit ugly for long titles. Better remove it.
So you have been able to make the icon stacking work? 

Can you push a refreshed version on your branch so I can apply?

**Comment by apat59** [comment]
I've removed the icon but I'm not sure how I can add another commit to this existing pull request. Should I simply create another pull request?

About the stacked icons: no it doesn't work. The best you can do is to stack them but since the "inverse" colour and and "2x" sizing are ignored, the resulting is horrible.

**Comment by stliu** [comment]
you can just push the commit to your original branch on github, it will automatically be included in the pull request

**Comment by apat59** [comment]
thanks Strong :)

**Comment by emmanuelbernard** [comment]
Sorry for the long delay, it is applied now.

**Comment by apat59** [comment]
thanks

**Pull request closed without merging**
