### PR TITLE
Update footer to new style guidelines

### PR DESCRIPTION
**Pull request by Sanne**
I've seen other projects migrating to a new improved style.

The guidelines provide a new header and a new footer; I applied the footer only but I think we could apply this already, it's simpler and lighter.

I'm not sure if we want to upgrade the header too, it's quite different and I'm not sure how it should integrate with our logo.

Guidelines can be seen on https://mojo.redhat.com/docs/DOC-958947

### CODE REVIEW

**Comment by yrodiere** [comment]
Looks fine!

> I'm not sure if we want to upgrade the header too, it's quite different and I'm not sure how it should integrate with our logo.

And even just integrating just the logos seems complicated: they don't have a version of the RedHat Developers logo for white background...

Maybe we could just drop the current style of our menu bar and go for something similar to [the Infinispan website](http://infinispan.org/)?

**Comment by Sanne** [comment]
> go for something similar to the Infinispan website?

Yes, the footer is from the same style. I just didn't have time to try the headers as well, nor am I sure if we'd all agree with that.. the footer seemed a simpler start.

**Comment by DavideD** [comment]
Last time I heard, the website needed to be consistent with the others like
http://www.jboss.org/

Make sure to check with Emmanuel or whoever is responsible before changing
header and footer.

**Comment by Sanne** [comment]
@DavideD sure, I know about that. Read the doc I've linked to: the style I'm applying is the revised version of what jboss.org projects are supposed to use. The one we're using is years old.

**Comment by gsmet** [comment]
OK... so the new website includes the RH and RH developers logos at the bottom of the page.

We still have the old header as the new one is really too agressive and don't go well with our website.

I know some of the projects took some liberty with the header: typically http://wildfly-swarm.io/ for instance just includes 2 text links on a white background.

Let's close it for now.

**Pull request closed without merging**
