### PR TITLE
Various minor, plus new Hibernate Search releases

### PR DESCRIPTION
**Pull request by Sanne**

### CODE REVIEW

**Comment by hferentschik** [comment]
No Jira key?

**Comment by Sanne** [comment]
do we need to open JIRAs for each website change?
AFAIK others just push on master without even the peer review, I thought I was being over-zealous already :)

**Comment by hferentschik** [comment]
> do we need to open JIRAs for each website change?

Always good with an issue key. If nothing else it makes the commit log looks prettier :-)

> AFAIK others just push on master without even the peer review

Sure. Either way, if not a Jira key then some more descriptive commit message might be good. Something which helps placing the change into a given area of the site. I'll take care of it.

**Comment by hferentschik** [comment]
Merged with some additional changes to community page

**Pull request closed without merging**
