### PR TITLE
WEBSITE-132 & WEBSITE-113

### PR DESCRIPTION
**Pull request by hferentschik**
Not sure whether displaying the ORM version in the downloads section is enough for WEBSITE-113, but I think it makes a nice addition.

### CODE REVIEW

**Comment by emmanuelbernard** [comment]
The depends on works for me.
I saw a `{latest_stable}` on Validator's getting started page when rendering (CDI section)

**Comment by hferentschik** [comment]
> I saw a {latest_stable} on Validator's getting started page when rendering (CDI section)

checking ...

**Comment by hferentschik** [comment]
> I saw a {latest_stable} on Validator's getting started page when rendering (CDI section)

I forgot to add the '[subs="verbatim,attributes"]' pixie dust. Should work now.

**Comment by hferentschik** [comment]
btw, should the pull request be against _staging_ or _production_, or both?

**Comment by emmanuelbernard** [comment]
staging is fine

**Comment by hferentschik** [comment]
> staging is fine

ok

**Pull request closed without merging**
