### PR TITLE
WEBSITE-140 & WEBSITE-130

### PR DESCRIPTION
**Pull request by hferentschik**
ATM the hib_docs redirects are regenerated when building the site. We could consider checking the generated files in and disabling the config in the pipeline.rb

### CODE REVIEW

**Comment by emmanuelbernard** [comment]
Other than that it's minor but I am not a fan of file names that mix `_` and `-`

**Comment by emmanuelbernard** [comment]
To me generation is fine BTW.

**Comment by hferentschik** [comment]
> Other than that it's minor but I am not a fan of file names that mix _ and -

No me either. I'll change that ...

> To me generation is fine BTW

Is is my preference as well, unless we at some stage hit a problem in how fast the site rebuilds.

**Comment by hferentschik** [comment]
@emmanuelbernard Pushed an update. Changed the file names to only use '-' and added the conditional statement around the redirect creation. It makes it a bit harder to test, but I guess, what I should really do is add a rspec for this extension. Next time ;-)

**Pull request closed without merging**
