### PR TITLE
WEBSITE-99 Revert original image for the tabzilla button

### PR DESCRIPTION
**Pull request by DavideD**
https://hibernate.atlassian.net/browse/WEBSITE-99

### CODE REVIEW

**Comment by DavideD** [comment]
I've added a commit put the button in front of the navbar, I think it looks nicer.
Feel free to remove the second commit if it is better: https://github.com/DavideD/hibernate.org/commit/55d2eccb0b96cb4200c7527d8b92b53db8158692

**Comment by emmanuelbernard** [comment]
I've requested feedback from the design team hat must validate our use of Red Hat visual elements. The first commit is in production now. The second in staging.

**Comment by DavideD** [comment]
I'm trying the site on my mobile and I have to admit that in the staging version, it is quite hard to press the top menu icon instead of the toggle button or viceversa. Is it just me?

**Comment by emmanuelbernard** [comment]
It's fine for me but I can see that The new approach might alleviate the problem though.

**Pull request closed without merging**
