### PR TITLE
WEBSITE-94

### PR DESCRIPTION
**Pull request by hferentschik**

### CODE REVIEW

**Comment by emmanuelbernard** [comment]
This PR does not rebase properly on production.

**Comment by hferentschik** [comment]
> This PR does not rebase properly on production.

that's because it was sitting there for a while now. I guess yesterdays changes might cause the conflicts. I'll have a look...

**Comment by hferentschik** [comment]
@emmanuelbernard rebased on top of production

**Comment by emmanuelbernard** [comment]
I thought I had swept them but apparently not.

**Pull request closed without merging**
