### PR TITLE
WEBSITE-249 Adding a landing page for obsolete ORM documentation links

### PR DESCRIPTION
**Pull request by hferentschik**

### CODE REVIEW

**Comment by emmanuelbernard** [comment]
This will need a rebase off production.

**Comment by emmanuelbernard** [comment]
I think this improves over the existing. It makes for a softer landing page.

**Comment by hferentschik** [comment]
Rebased and fixed wrong URL.

> I think this improves over the existing. It makes for a softer landing page.

Right. It gives more specific information about stale documentation links. I think we can use a similar approach for other groups links which seems to get hits every now and then.

**Comment by hferentschik** [comment]
Applied suggested edits, re-based and merged.

**Pull request closed without merging**
