### PR TITLE
Add search FAQ entry on exclusive_index_use

### PR DESCRIPTION
**Pull request by emmanuelbernard**
@Sanne Am I making sense with this entry. This has been triggered by https://forum.hibernate.org/viewtopic.php?f=9&t=1039407&p=2484473#p2484473

### CODE REVIEW

**Comment by Sanne** [comment]
No not exactly, if you forget to set "exclusive=false" then both nodes would attempt to acquire the lock (and keep it) for as long as the SessionFactory is open.
So one node would succeed and work fine, the other node would get a lock acquisition timeout exception.

But it's not related to "visibility". I'll keep your edit about "it's a configuration issue" and apply that.

**Comment by emmanuelbernard** [comment]
So we no longer can share a file directory between instances like we could before @Sanne ? Or was it that it required a long timeout and search does not expose the timeout setting?

**Comment by emmanuelbernard** [comment]
I thought we had a slow but shared lock approach in the old days.

**Comment by Sanne** [comment]
> So we no longer can share a file directory between instances like we could before @Sanne ?

Yes you can, just disable this option. But unless you are sure that only one node will attempt to write, it will be slow and you'll probably have some timeouts.

> Or was it that it required a long timeout and search does not expose the timeout setting?

Lucene doesn't expose the timeout. I've tried to patch that but it doesn't make much sense to change as there is no way that it can be made to be "fair".

> I thought we had a slow but shared lock approach in the old days.

Yes just disable this and you're back to old behaviour, but it wasn't just slow, it was rarely acceptable.

**Pull request closed without merging**
