### PR TITLE
WEBSITE-166 Adding Awestruct sitemap plugin (added prior to redirect cre...

### PR DESCRIPTION
**Pull request by hferentschik**
...ation)

### CODE REVIEW

**Comment by hferentschik** [comment]
I guess adding a sitemap cannot hurt. Whether it improves ranking/indexing is a different matter

**Comment by emmanuelbernard** [comment]
So the output seems a bit strange to me
- everything is marked as changefreq = never which is not the case
- `/validator/contribute/hibernate-validator.xml`: what is that?
- `CNAME` is indexed
- `/google9616cdec3070007c.html` is indexed
- `/tabcontent/` is indexed

Not being a sitemap expert, I'm not sure what the implications are to having a incorrect or partial sitemap.

BTW Are all URL mapped?

```
<?xml version="1.0" encoding="utf-8" ?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>http://localhost:4242/404.html</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/CNAME</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/README/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/community/governance/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/community/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/community/license/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/community/we-lost-that-content/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/dtd/hibernate-configuration-2.0.dtd</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/dtd/hibernate-configuration-3.0.dtd</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/dtd/hibernate-configuration.dtd</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/dtd/hibernate-generic.dtd</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/dtd/hibernate-mapping-1.1.dtd</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/dtd/hibernate-mapping-2.0.dtd</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/dtd/hibernate-mapping-3.0.dtd</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/dtd/hibernate-mapping.dtd</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/dtd/hibernate-reverse-engineering-3.0.dtd</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/dtd/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/google9616cdec3070007c.html</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/ogm/contribute/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/ogm/documentation/getting-started/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/ogm/documentation/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/ogm/downloads/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/ogm/faq/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/ogm/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/ogm/roadmap/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/ogm/support/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/orm/certification/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/orm/contribute/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/orm/documentation/getting-started/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/orm/documentation/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/orm/documentation/old-jpa-migration-guide/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/orm/downloads/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/orm/faq/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/orm/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/orm/roadmap/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/orm/support/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/orm/tooling/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/orm/what-is-an-orm/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/others/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/search/contribute/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/search/documentation/getting-started/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/search/documentation/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/search/downloads/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/search/faq/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/search/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/search/roadmap/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/search/support/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/survival-guide/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/tabcontent/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/tools/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/validator/contribute/hibernate-validator.xml</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/validator/contribute/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/validator/documentation/getting-started/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/validator/documentation/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/validator/downloads/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/validator/faq/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/validator/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/validator/roadmap/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/validator/support/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
  <url>
    <loc>http://localhost:4242/validator/tooling/</loc>
    <lastmod>2014-04-04</lastmod>
    <priority>0.1</priority>
    <changefreq>never</changefreq>
  </url>
</urlset>
```

**Comment by gunnarmorling** [comment]
I think hibernat-validator.xml is the formatting template which is
referenced from the contribution guide. It shouldnt be in the sitemap.
Am 04.04.2014 16:07 schrieb "Emmanuel Bernard" notifications@github.com:

**Comment by hferentschik** [comment]
> I think hibernat-validator.xml is the formatting template which is referenced from the contribution guide. It shouldnt be in the sitemap.

Correct, I excluded it.

**Comment by hferentschik** [comment]
> So the output seems a bit strange to me ...

I excluded the files you mentioned. Also, I changed the default priority to 0.5. According to the plugin docs this should be the default anyways, but looking at the code it is 0.1. I looked at Google's sitemap and they use 0.5 on their pages.

 I changed _changefreq_ to monthly. I would prefer to leave it off (Google does the same ;-)), but that's not configurable. Then we would need to modify the sitemap extension. Would monthly be a fair trade-off? It is a hint only anyways. See also http://www.sitemaps.org/protocol.html

I also added the sitemap url to robots.txt as one way of "registering" the sitemap.

**Comment by hferentschik** [comment]
> BTW Are all URL mapped?

That depends how you see it. The redirects are not mapped. That's because I placed the sitemap extension before the redirect one. Do you think redirect pages should be listed as well?

**Comment by emmanuelbernard** [comment]
> That depends how you see it. The redirects are not mapped. That's because I placed the sitemap extension before the redirect one. Do you think redirect pages should be listed as well?

No, probably not. Not all of them at any rate.

**Comment by emmanuelbernard** [comment]
> I changed changefreq to monthly. I would prefer to leave it off (Google does the same ;-)), but that's not configurable. Then we would need to modify the sitemap extension. Would monthly be a fair trade-off? It is a hint only anyways. See also http://www.sitemaps.org/protocol.html

I did some research and sitemaps are particularly useful for websites using flash (and where indexing is doomed) and to hint the crawler of dynamic pages that are sensitive to form and user entries.

Based on this, my preference is to let the crawler naturally navigate our site rather than use the sitemap. We have a very straightforward structure and all interesting links are reachable from `/` (via cascading).

**Comment by hferentschik** [comment]
> I did some research and sitemaps are particularly useful for websites using flash (and where indexing is doomed) and to hint the crawler of dynamic pages that are sensitive to form and user entries.

Fair enough. I have no strong feelings about this one. Just toying around. Regarding _sitemap.xml_, my understanding was that adding it is a good idea regardless. There is no guarantee that you get a better ranking or so, but it is "good style". Not sure, how sitemap helps at all with Flash, but maybe that's because I have no clue about Flash to begin with. May I ask where you found your information?

**Comment by emmanuelbernard** [comment]
On 08 Apr 2014, at 20:17, Hardy Ferentschik notifications@github.com wrote:

> I did some research and sitemaps are particularly useful for websites using flash (and where indexing is doomed) and to hint the crawler of dynamic pages that are sensitive to form and user entries.
> 
> Fair enough. I have no strong feelings about this one. Just toying around. Regarding sitemap.xml, my understanding was that adding it is a good idea regardless. There is no guarantee that you get a better ranking or so, but it is "good style". Not sure, how sitemap helps at all with Flash, but maybe that's because I have no clue about Flash to begin with. May I ask where you found your information?
> 
> The one resource that tipped me over was https://en.wikipedia.org/wiki/Site_map and the fact that defining a monthly frequency is a bit annoying.

I thought about flash and indexing + shadow sites a lot so I have a head start :)

**Comment by hferentschik** [comment]
> The one resource that tipped me over was https://en.wikipedia.org/wiki/Site_map

I see

>  defining a monthly frequency is a bit annoying

Right. I would have liked to leave it off

> I thought about flash and indexing + shadow sites a lot so I have a head start :)

aha aha

**Pull request closed without merging**
