### PR TITLE
Remove the now dated carousel

### PR DESCRIPTION
**Pull request by gsmet**
hibernate-index

### CODE REVIEW

**Comment by gsmet** [comment]
Maybe `What's new` would be better than `News`. @yrodiere suggestions?

**Comment by yrodiere** [comment]
Nice. That auto-scrolling was annoying IMO, so I'm glad to get rid of it.

> Maybe `What's new` would be better than `News`.

Agreed. Or "Latest news". Whatever works for you.

> @yrodiere suggestions?

When we had a ribbon, I think the use of brown color could be defended; now that it's a simple icon, I think it clashes a bit with the theme. Using the same grey as the other icons below would make more sense, IMO. Or, if you must, the same "gold" color you're using to underline section titles.

Also, I think a "more" button, redirecting to the front page of in.relation.to, would make sense here.

**Comment by gsmet** [comment]
Screenshot 2022-03-07 at 13-01-31 Hibernate Everything data - Hibernate

**Comment by gsmet** [comment]
I think a shinier color would be better for the icons but I suppose we can live with the grey.

**Review by yrodiere — APPROVED** [review]

**Comment by yrodiere** [comment]
Merged, thanks

**Pull request merged**
