### PR TITLE
WEBSITE-228 Refactoring release file parser to ignore data which is not ...

### PR DESCRIPTION
**Pull request by hferentschik**
...in 'release' directory

### CODE REVIEW

**Comment by hferentschik** [comment]
@emmanuelbernard, did you have time to look at it? Ok to merge?

**Comment by emmanuelbernard** [comment]
It still does not play nice with the DataDir extension, correct? Since we managed to not use it so far, we can delay that fix I suppose.

**Comment by hferentschik** [comment]
> It still does not play nice with the DataDir extension, correct? 

It should. Now only files in the `releases` directory are considered. The change is neutral for hibernate.org, since the outcome is the same. Personally, I think the code is easier now. AFAICT it also fixes the problem with the DataDir extension. At the very least you can now have other type of files and directories in the _data directory.

**Comment by emmanuelbernard** [comment]
Applied

**Comment by hferentschik** [comment]
thanks

**Pull request closed without merging**
