### PR TITLE
WEBSITE-110 Move Hibernate logo above navigation

### PR DESCRIPTION
**Pull request by DavideD**
https://hibernate.atlassian.net/browse/WEBSITE-110

### CODE REVIEW

**Comment by hferentschik** [comment]
@DavideD OOI, do pull request not get automatically build and deployed on staging. 

As food for thought, maybe we need yet another site (e.g. demo.hibernate.org). Staging being the site where we build for production and where we can inspect pull request changes and demo (or whatever) where you can deploy experiments. @emmanuelbernard, @Sanne thoughts?

**Comment by Sanne** [comment]
Sorry above comment was me.

> An auto-staging feature would be interesting indeed.
> 
> Problem is what would happen with multiple PRs? We'd at least need to know at which PR you're looking at when going to $URL. Maybe embed a PR in the footer? Or have a "staging site" where I can look at deployed in the scope of the CI build workspace?

**Comment by hferentschik** [comment]
> An auto-staging feature would be interesting indeed.

Right. Somehow I feel our workflow is not really optimal yet. We probably should take this to the mailing list. 

> Problem is what would happen with multiple PRs? We'd at least need to know at which PR you're looking at when going to $URL. 

Could be done

>  Or have a "staging site" where I can look at deployed in the scope of the CI build workspace?

That would be optimal imo. Instead of copying the built site to the Apache directory, we should serve it from the workspace or a build archive directory. URLs could be of the form http://staging.hibernate.org/pr-001/
Question is whether we get problems with link targets and navigation within the site. Still, worth investigating imo

**Comment by Sanne** [comment]
+1 to all that but.. would we then also use the "Merge pull request" button on github?
Because if we don't, at some point we still need to open a terminal, which makes the infrastructure work less valuable I think.

**Comment by hferentschik** [comment]
> +1 to all that but.. would we then also use the "Merge pull request" button on github?

I think it might be a good idea.

**Comment by Sanne** [comment]
ok I'll look at how such a build job could work.

**Comment by hferentschik** [comment]
> ok I'll look at how such a build job could work.

sweet

**Pull request merged**
